# Generated by Django 3.2.7 on 2021-09-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_abbr', models.CharField(max_length=12)),
                ('major_title', models.TextField()),
                ('gpa_2yr', models.JSONField(null=True)),
                ('gpa_5yr', models.JSONField(null=True)),
            ],
        ),
    ]
