# Generated by Django 3.2.7 on 2021-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='major_home_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='program_code',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
