# Generated by Django 3.2.7 on 2021-10-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.CharField(default='0', max_length=12),
            preserve_default=False,
        ),
    ]
