# Generated by Django 3.2.7 on 2021-10-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0006_course_gpa_distro'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='concurrent_courses',
            field=models.JSONField(null=True),
        ),
    ]
