# Generated by Django 3.2.7 on 2021-10-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0007_course_concurrent_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=10)),
                ('prereq_graph', models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prereq_graph',
            field=models.JSONField(null=True),
        ),
    ]
