# Generated by Django 3.2.7 on 2021-11-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0008_auto_20211029_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='postreq_list',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='prereq_list',
            field=models.JSONField(null=True),
        ),
    ]
