# Generated by Django 3.2.7 on 2021-11-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0009_curriculum_course_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_offered',
            field=models.TextField(null=True),
        ),
    ]
