# Generated by Django 3.2.7 on 2021-11-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0010_auto_20211109_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='COIRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coi_range', models.IntegerField(choices=[(0, '0-1'), (1, '1-2'), (2, '2-3'), (3, '3-4'), (4, '4-5')])),
                ('percent_in_range', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400')])),
                ('coi_score', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='coi_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='average_coi_score',
            field=models.FloatField(null=True),
        ),
    ]
