# Generated by Django 3.2.7 on 2021-11-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0011_auto_20211111_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.CharField(max_length=32)),
                ('has_viewed_welcome', models.BooleanField(default=False)),
                ('first_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
