# Generated by Django 3.2.7 on 2021-11-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0011_auto_20211111_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_campus',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
