# Generated by Django 3.2.7 on 2021-11-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0012_course_course_campus'),
        ('pathways', '0012_user'),
    ]

    operations = [
    ]
