# Generated by Django 3.2.9 on 2021-12-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0013_merge_0012_course_course_campus_0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='credential_code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='credential_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='credential_title',
            field=models.TextField(null=True),
        ),
    ]
