# Generated by Django 3.2.13 on 2022-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0014_auto_20211220_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
                ('hash', models.CharField(max_length=32)),
                ('imported_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
