# Generated by Django 3.2.13 on 2022-06-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0015_dataimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uwnetid',
            field=models.CharField(max_length=32),
        ),
    ]
