# Generated by Django 3.2.13 on 2022-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0017_auto_20220624_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_viewed_bottleneck_banner',
            field=models.BooleanField(default=False),
        ),
    ]
