# Generated by Django 3.2.16 on 2022-10-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0020_user_has_viewed_outcomes_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereq_string',
            field=models.TextField(null=True),
        ),
    ]
