# Generated by Django 3.2.16 on 2023-01-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0021_course_prereq_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='curric_name',
            field=models.TextField(null=True),
        ),
    ]
