# Generated by Django 3.2.16 on 2023-01-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0022_curriculum_curric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department_abbrev',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
