# Generated by Django 4.2.20 on 2025-03-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0024_user_has_viewed_coi_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='is_stem',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SimilarMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('similarity_description', models.TextField(choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Mid'), ('H', 'High')])),
                ('similar_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_major', to='pathways.major')),
                ('source_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_major', to='pathways.major')),
            ],
        ),
    ]
