# Generated by Django 4.2.20 on 2025-05-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0025_major_is_stem_similarmajor'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='program_verind_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
