version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: pathways_app
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    volumes:
      - ./pathways:/app/pathways
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  devtools:
    build:
      context: .
      target: wpack
    restart: always
    container_name: pathways_devtools
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./pathways_vue:/app/pathways_vue
      - statics-volume:/static
    command: npx webpack --watch --mode=development
    stdin_open: true
    tty: true
volumes:
  statics-volume:
